# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Front.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(757, 688)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Mistral")
        font.setPointSize(26)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.formFrame = QtWidgets.QFrame(self.tab_3)
        self.formFrame.setMaximumSize(QtCore.QSize(16777215, 300))
        self.formFrame.setStyleSheet("background-color: rgba( 0, 0, 0, 75% );\n"
"    border-radius: 10px;")
        self.formFrame.setObjectName("formFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.formFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.maxInput = QtWidgets.QLineEdit(self.formFrame)
        self.maxInput.setStyleSheet("color:rgb(255, 255, 255);")
        self.maxInput.setObjectName("maxInput")
        self.gridLayout_2.addWidget(self.maxInput, 1, 1, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color: rgba( 0, 0, 0, 0% )")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color: rgba( 0, 0, 0, 0% )")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.functionInput = QtWidgets.QLineEdit(self.formFrame)
        self.functionInput.setStyleSheet("color:rgb(255, 255, 255);")
        self.functionInput.setObjectName("functionInput")
        self.gridLayout_2.addWidget(self.functionInput, 2, 1, 1, 3)
        self.minInput = QtWidgets.QLineEdit(self.formFrame)
        self.minInput.setStyleSheet("color:rgb(255, 255, 255);")
        self.minInput.setText("")
        self.minInput.setObjectName("minInput")
        self.gridLayout_2.addWidget(self.minInput, 0, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color: rgba( 0, 0, 0, 0% )")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.plot = QtWidgets.QPushButton(self.formFrame)
        self.plot.setStyleSheet(" background-color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"color:black;")
        self.plot.setAutoDefault(False)
        self.plot.setDefault(False)
        self.plot.setFlat(False)
        self.plot.setObjectName("plot")
        self.gridLayout_2.addWidget(self.plot, 3, 1, 1, 3)
        self.gridLayout_3.addWidget(self.formFrame, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(16)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Mistral")
        font.setPointSize(26)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.tab_4)
        self.widget.setObjectName("widget")
        self.gridLayout_4.addWidget(self.widget, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "FUNCTION PLOTTER"))
        self.label_3.setText(_translate("MainWindow", "Function"))
        self.label.setText(_translate("MainWindow", "Min"))
        self.label_2.setText(_translate("MainWindow", "Max"))
        self.plot.setText(_translate("MainWindow", "Plot"))
        self.label_6.setText(_translate("MainWindow", "Please enter a valid function with the following restrictions:\n"
"\n"
"Allowed operators: * + - / ^ ( )\n"
"Example: 2*x, (x^2) + 2, 2 + x\n"
"Single variable only: The function should contain only one variable, x.\n"
"Example: 2*x, x^2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "input"))
        self.label_5.setText(_translate("MainWindow", "GRAPH"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "graph"))
